baseurl = "https://zharr.is"
languageCode = "en-us"
title = "zharr.is"
author = "Zach Harris"
copyright = "Zach Harris"

enableEmoji = true
enableGitInfo = true

disableKinds = ['taxonomy', 'term']

disableFastRender = true        # Hugo 0.30
pygmentsUseClasses = true       # This applies to Chroma too.

# [module]
#   [[module.imports]]
#     disable = true
#     path = "github.com/kaushalmodi/hugo-bare-min-theme"

[[menu.main]]
name = "~"
url = "/"
weight = 1

[[menu.main]]
name = "whoami"
url = "/whoami"
weight = 2

[[menu.main]]
name = "writing"
url = "/writing"
weight = 3

[[menu.main]]
# name = "About"
# url = "/about"
# weight = 4

[params]
  description = "Zach Harris is a polygot software engineer with an insatiable curiosity."
  mainSection = "posts"
  # mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 1
  tagsOverview = false
  tocInline = true
  # showProjectsList = true
  # projectsUrl = "https://github.com/zacaytion"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

[[params.social]]
  name = "github"
  link = "https://github.com/zacaytion"

[[params.social]]
  name = "email"
  link = "info@zharr.is" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/z-a-h/"

[markup]
  [markup.highlight]
    style = "monokai"
    tabWidth = 2

## For PurgeCSS
[build]
  writeStats = true

