[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  HUGO_VERSION = "0.27"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.27"

[context.deploy-preview]
  command = "npm run build-preview"
